server:
  port: 80

mybatis:
  config-location: classpath:/mybatis-config.xml
  type-handlers-package: pmm.pbm.data.base.entity
  mapper-locations: classpath:**/mapper/*.xml

logging:
  level:
    pmm.pbm: DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG

my:
  paging:
    shown-pages: 8
    default-limit: 10

spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost/pmm?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF-8
    username: pmm
    password: 123456
    type: com.mchange.v2.c3p0.ComboPooledDataSource

  thymeleaf:
    cache: false

  messages:
    basename: i18n/messages

  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  resources:
    chain:
      cache: false

  mvc:
    date-format: yy-M-d
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://192.168.1.100/test?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: tuozhen
    type: com.mchange.v2.c3p0.ComboPooledDataSource
  thymeleaf:
    cache: false

  messages:
    basename: i18n/messages

  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  resources:
    chain:
      cache: false

  mvc:
    date-format: yy-M-d