package pmm.pbm.data.base.entity;

import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import pmm.pbm.data.base.support.Entity;

@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
public class Author extends Entity implements Serializable {
    /**
     * Name of author
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Brief introduction of author
     *
     * @mbg.generated
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pbm_author
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}