package pmm.pbm.data.base.entity;

import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import pmm.pbm.data.base.support.Entity;

@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
public class Book extends Entity implements Serializable {
    /**
     * Title of book
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Id of book author
     *
     * @mbg.generated
     */
    private Integer authorId;

    /**
     * Id of book genre
     *
     * @mbg.generated
     */
    private Integer genreId;

    /**
     * Brief introduction of book
     *
     * @mbg.generated
     */
    private String intro;

    /**
     * Id of book cover
     *
     * @mbg.generated
     */
    private Integer coverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pbm_book
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}