package pmm.pbm.data.base.entity;

import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import pmm.pbm.data.base.support.Entity;

@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
public class BookTag extends Entity implements Serializable {
    /**
     * Id of book
     *
     * @mbg.generated
     */
    private Integer bookId;

    /**
     * Id of tag
     *
     * @mbg.generated
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pbm_book_tag
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}