package pmm.pbm.data.base.entity;

import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import pmm.pbm.data.base.support.Entity;

@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
public class Log extends Entity implements Serializable {
    /**
     * Id of operator
     *
     * @mbg.generated
     */
    private String operatorId;

    /**
     * Id of source
     *
     * @mbg.generated
     */
    private Byte sourceId;

    /**
     * Time of modification
     *
     * @mbg.generated
     */
    private Long time;

    /**
     * Type of modification
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Id of record modified
     *
     * @mbg.generated
     */
    private String targetId;

    /**
     * Description of modification
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pmm_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}