package pmm.pbm.data.base.entity;

import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import pmm.pbm.data.base.support.Entity;

@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
public class Tag extends Entity implements Serializable {
    /**
     * Name of tag
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Brief introduction of tag
     *
     * @mbg.generated
     */
    private String intro;

    /**
     * Rank of tag
     *
     * @mbg.generated
     */
    private Integer rank;

    /**
     * Enable state
     *
     * @mbg.generated
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pbm_tag
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}